spring.application.name=eazystore

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:~/eazystore;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
